import type { Shot } from "./tours";

// Rajesh's photographs, captioned the way he captions them: species · place · month.
// Old-site images carry species and region in their original filenames; Instagram images use his captions.

export type GalleryGroup = { id: string; name: string; shots: Shot[] };

export const gallery: GalleryGroup[] = [
  {
    id: "himalaya",
    name: "Himalaya",
    shots: [
      { slug: "grandala-flock-lachen", caption: "Grandalas · Lachen, North Sikkim · Mar 2019" },
      { slug: "g-satyr-tragopan", caption: "Satyr Tragopan · Bhutan" },
      { slug: "g-himalayan-cutia", caption: "Himalayan Cutia · Bhutan" },
      { slug: "g-sclaters-monal-white-tailed-2017", caption: "Sclater's Monal (white-tailed) · Sela Pass · May 2017" },
      { slug: "fire-tailed-sunbird-tawang", caption: "Fire-tailed Sunbird · Tawang, Arunachal Pradesh · May 2026" },
      { slug: "g-cheer-pheasant", caption: "Cheer Pheasants · Uttarakhand" },
      { slug: "g-fire-tailed-myzornis", caption: "Fire-tailed Myzornis · Dochula, Bhutan · Apr 2019" },
      { slug: "g-golden-bush-robin", caption: "Golden Bush Robin · Munsiyari · Jan 2021" },
      { slug: "g-bearded-vulture", caption: "Bearded Vulture · Uttarakhand" },
      { slug: "g-mrs-goulds-sunbird", caption: "Mrs Gould's Sunbird · Trongsa, Bhutan · Apr 2019" },
      { slug: "g-beautiful-nuthatch", caption: "Beautiful Nuthatch · Arunachal Pradesh" },
      { slug: "g-yellow-billed-blue-magpie", caption: "Yellow-billed Blue Magpie · Munsiyari · Nov 2020" },
      { slug: "arunachal-goulds-shortwing", caption: "Gould's Shortwing · Tawang · May 2026" },
      { slug: "g-scarlet-finch", caption: "Scarlet Finch · Munsiyari · Dec 2019" },
      { slug: "g-wards-trogon", caption: "Ward's Trogon · Bhutan" },
      { slug: "g-beautiful-rosefinch", caption: "Beautiful Rosefinch · Chhitkul · Jun 2019" },
      { slug: "g-snow-partridge", caption: "Snow Partridge · Tungnath · Dec 2025" },
      { slug: "g-golden-eagle", caption: "Golden Eagle · Uttarakhand" },
      { slug: "g-spotted-forktail", caption: "Spotted Forktail · Nalni · May 2020" },
      { slug: "g-sultan-tit", caption: "Sultan Tit · Khupa, Arunachal · Feb 2021" },
      { slug: "g-red-headed-bullfinch", caption: "Red-headed Bullfinch · Pele La, Bhutan · Apr 2019" },
      { slug: "g-white-bellied-redstart", caption: "White-bellied Redstart · Himachal Pradesh" },
    ],
  },
  {
    id: "ladakh-kashmir",
    name: "Ladakh & Kashmir",
    shots: [
      { slug: "g-tsaka-la-trio", caption: "Tickell's Leaf Warbler, Chinese Rubythroat, Robin Accentor · Tsaka La · Jun 2022" },
      { slug: "ladakh-tit-warbler", caption: "White-browed Tit-Warbler · Ladakh" },
      { slug: "g-tibetan-snowcock", caption: "Tibetan Snowcock · Ladakh" },
      { slug: "ladakh-bluethroat", caption: "Bluethroat · Ladakh" },
      { slug: "g-great-rosefinch", caption: "Great Rosefinch · Ladakh · Jun 2019" },
      { slug: "ladakh-tibetan-partridge", caption: "Tibetan Partridge · Ladakh" },
      { slug: "long-eared-owls-kashmir", caption: "Long-eared Owls · Ganderbal, Kashmir · Mar 2022" },
      { slug: "g-orange-bullfinch", caption: "Orange Bullfinch · Dachigam · Dec 2020" },
      { slug: "g-kashmir-nuthatch", caption: "Kashmir Nuthatch · Yusmarg · Feb 2022" },
      { slug: "g-brambling-tree", caption: "The Brambling tree · Kangan, Kashmir · Feb 2022" },
    ],
  },
  {
    id: "home-patch",
    name: "Kaladhungi & Corbett",
    shots: [
      { slug: "paradise-flycatcher-kaladhungi", caption: "Indian Paradise Flycatcher · Kaladhungi · May 2026" },
      { slug: "peacock-bijrani", caption: "Indian Peafowl dancing · Bijrani, Corbett · Mar 2016" },
      { slug: "great-slaty-woodpecker-2026", caption: "Great Slaty Woodpecker · Kaladhungi · Jan 2026" },
      { slug: "g-collared-owlet", caption: "Collared Owlet · Kalagarh, Corbett landscape · Feb 2021" },
      { slug: "g-spot-bellied-eagle-owl", caption: "Spot-bellied Eagle Owl · Dhikala, Corbett · May 2019" },
      { slug: "g-common-green-magpie", caption: "Common Green Magpie · Kaladhungi · Jul 2020" },
      { slug: "parwali-tigress", caption: "Parwali tigress · Dhikala, Corbett · Mar 2015" },
      { slug: "g-golden-fronted-leafbird", caption: "Golden-fronted Leafbird · Kaladhungi · Aug 2019" },
      { slug: "lesser-yellownape", caption: "Lesser Yellownape · Sattal · Dec 2024" },
      { slug: "g-collared-falconet", caption: "Collared Falconet · Corbett · Feb 2021" },
      { slug: "vinaceous-rosefinch", caption: "Vinaceous Rosefinch · Nainital" },
      { slug: "oriental-scops-owl", caption: "Oriental Scops Owl, rufous · Kaladhungi · 2026" },
      { slug: "g-great-hornbill-flight", caption: "Great Hornbill · Kaladhungi · Jun 2016" },
      { slug: "yellow-breasted-bunting", caption: "Yellow-breasted Bunting · Baur Reservoir · Jan 2021" },
    ],
  },
  {
    id: "north-east",
    name: "North-East & Bengal",
    shots: [
      { slug: "mishmi-blyths-tragopan", caption: "Blyth's Tragopan · Mishmi Hills · Apr 2022" },
      { slug: "g-violet-cuckoo", caption: "Violet Cuckoo with a caterpillar · Lower Mahananda · Aug 2026" },
      { slug: "g-pale-headed-woodpecker", caption: "Pale-headed Woodpecker · Rongtong, West Bengal · Aug 2026" },
      { slug: "g-small-niltava", caption: "Small Niltava · Gangtok · Mar 2019" },
      { slug: "g-scarlet-minivet", caption: "Scarlet Minivet · Phodong, Sikkim · Mar 2019" },
      { slug: "g-jerdons-baza", caption: "Jerdon's Baza · Rongtong, West Bengal · Aug 2026" },
      { slug: "g-yellow-vented-flowerpecker", caption: "Yellow-vented Flowerpecker · Dosdewa, Assam · Oct 2022" },
      { slug: "namdapha-blyths-kingfisher", caption: "Blyth's Kingfisher · Namdapha · Nov 2024" },
      { slug: "g-wards-trogon-eaglenest", caption: "Ward's Trogon · Eaglenest · Apr 2022" },
      { slug: "g-black-baza", caption: "Black Baza · Shivkhola, West Bengal · Aug 2026" },
    ],
  },
  {
    id: "abroad",
    name: "Abroad",
    shots: [
      { slug: "colombia-rainbow-bearded-thornbill", caption: "Rainbow-bearded Thornbill · Colombia · Jul 2026" },
      { slug: "costarica-quetzal", caption: "Resplendent Quetzal · Costa Rica · Mar 2023" },
      { slug: "png-flame-bowerbird", caption: "Flame Bowerbird · Papua New Guinea · Aug 2024" },
      { slug: "mongolia-eagle-fox", caption: "Golden Eagle · Mongolia · Oct 2025" },
      { slug: "peru-paradise-tanager", caption: "Paradise Tanager · Peru · Jul 2026" },
      { slug: "srilanka-blue-magpie", caption: "Sri Lanka Blue Magpie · Sinharaja · Dec 2019" },
      { slug: "madagascar-gecko", caption: "Eben's Leaf-tailed Gecko · Madagascar · Oct 2024" },
      { slug: "colombia-multicolored-tanager", caption: "Multicolored Tanager · Colombia · Jul 2026" },
      { slug: "borneo-black-crowned-pitta", caption: "Black-crowned Pitta · Borneo · Jul 2025" },
      { slug: "costarica-red-headed-barbet", caption: "Red-headed Barbet · Costa Rica · Feb 2024" },
      { slug: "mongolia-pallas-cat", caption: "Pallas's Cat · Mongolia · Oct 2025" },
      { slug: "colombia-cock-of-the-rock", caption: "Andean Cock-of-the-rock · Colombia · Jul 2026" },
      { slug: "srilanka-serendib-scops-owl", caption: "Serendib Scops Owl · Sri Lanka" },
      { slug: "malaysia-rusty-naped-pitta", caption: "Rusty-naped Pitta · Fraser's Hill · Jul 2025" },
    ],
  },
  {
    id: "night-and-land",
    name: "Night & landscape",
    shots: [
      { slug: "panchachuli-dawn", caption: "Panchachuli · Munsyari · Dec 2024" },
      { slug: "mongolia-ger-stars", caption: "Star trails over the gers · Mongolia · Oct 2025" },
      { slug: "ladakh-milky-way-pangong", caption: "Milky Way · Pangong Tso · Sep 2026" },
      { slug: "milieu-villa-milky-way", caption: "Milky Way over the house · Kaladhungi" },
      { slug: "vyas-valley-kailash", caption: "The Vyas valley, on the Tibet border · Uttarakhand" },
      { slug: "mongolia-camels", caption: "Bactrian camels · Mongolia · Oct 2025" },
      { slug: "barati-rau-waterfall", caption: "Barati Rau waterfall · Kaladhungi · Jan 2026" },
      { slug: "panchachuli-sunset", caption: "Panchachuli at sunset · Munsyari · Nov 2022" },
    ],
  },
];
