import type { PhotoSlug } from "./photo-sizes";

// Field reports, newest first. Each is Rajesh's own trip report from Instagram, cut down — the
// species totals, places and dates are his, and the eBird link is the checklist he shared.

export type Report = {
  id: string;
  when: string; // as a reader says it
  sort: string; // ISO month for ordering
  place: string;
  country: "India" | "Abroad";
  species?: string; // as published, e.g. "123" or "250+"
  extra?: string; // mammals, reptiles…
  guests?: string;
  text: string;
  ebird?: string;
  post: string; // Instagram post code
  photo?: PhotoSlug;
  tour?: string; // tour slug when it maps to a departure
};

export const reports: Report[] = [
  {
    id: "ladakh-2026-09",
    when: "10–20 Sep 2026",
    sort: "2026-09",
    place: "Ladakh passage migrants",
    country: "India",
    species: "123",
    extra: "16 mammals · 2 reptiles",
    guests: "8 participants",
    text: "Saker Falcon with a pika kill, full-frame Red-fronted Rosefinch, 500+ Tibetan Sandgrouse, a Eurasian Eagle-Owl on the ground. Wolf, wild ass, argali and four species of pika.",
    ebird: "https://ebird.org/tripreport/574386",
    post: "DdnMThiktDZ",
    photo: "ladakh-milky-way-pangong",
    tour: "ladakh-passage-migrants",
  },
  {
    id: "mahananda-2026-08",
    when: "Aug 2026",
    sort: "2026-08",
    place: "Lower Mahananda WLS, West Bengal",
    country: "India",
    species: "75",
    guests: "4 sessions",
    text: "A monsoon trip for cuckoos and bazas. Every target seen and photographed except Asian Emerald Cuckoo; a Pale-headed Woodpecker on an open perch was the bonus.",
    ebird: "https://ebird.org/tripreport/563180",
    post: "DcaHwopEiyI",
    photo: "g-pale-headed-woodpecker",
  },
  {
    id: "colombia-2026-07",
    when: "Jul 2026",
    sort: "2026-07",
    place: "Colombia, Central Andes",
    country: "Abroad",
    text: "Nine species of antpitta. Rainbow-bearded Thornbill at eye level at Termales del Ruiz, and the endemic Multicolored Tanager at two sites.",
    post: "Db9gexFSk0M",
    photo: "colombia-rainbow-bearded-thornbill",
    tour: "colombia",
  },
  {
    id: "peru-2026-07",
    when: "Jul 2026",
    sort: "2026-07",
    place: "Peru, Manu road cloud forest",
    country: "Abroad",
    text: "The whole group photographed the Paradise Tanager feeding low at Cock of the Rock Lodge, a tanager that has to be found in the wild, never at feeders.",
    post: "DbuBcbzy7Su",
    photo: "peru-paradise-tanager",
    tour: "peru",
  },
  {
    id: "malaysia-2026-06",
    when: "7–14 Jun 2026",
    sort: "2026-06",
    place: "Peninsular Malaysia",
    country: "Abroad",
    species: "153",
    extra: "2 gibbons · 3 macaques",
    text: "Great Argus and Malayan Peacock-Pheasant, the main targets, photographed and filmed, with Mountain Peacock-Pheasant and Rusty-naped and Garnet Pittas.",
    ebird: "https://ebird.org/tripreport/537372",
    post: "DZmJ97EDma8",
    photo: "malaysia-rusty-naped-pitta",
    tour: "peninsular-malaysia",
  },
  {
    id: "uttarakhand-2026-05",
    when: "May 2026 · 10 days",
    sort: "2026-05",
    place: "Uttarakhand: Kaladhungi to Darma Valley",
    country: "India",
    species: "222",
    guests: "Guests from Chennai, Bengaluru, Hyderabad",
    text: "Five zones in ten days, from Kaladhungi through Sattal, Chaukori and Munsyari to Darma Valley and Abbott Mount. Cheer Pheasant, Himalayan Monal, Great Slaty Woodpecker, Fire-capped Tit, Bearded Vulture.",
    ebird: "https://ebird.org/tripreport/530024",
    post: "DZFJ7ABmJf1",
    photo: "group-uttarakhand-2026",
  },
  {
    id: "arunachal-2026-05",
    when: "May 2026",
    sort: "2026-05",
    place: "Western Arunachal: Eaglenest to Tawang",
    country: "India",
    species: "256",
    text: "Good photographs of 150+ species, skulkers included: Sikkim Wedge-billed Babbler, Gould's Shortwing, a Himalayan Shortwing that danced on a stump for minutes.",
    ebird: "https://ebird.org/tripreport/523619",
    post: "DYdbqo6GE4P",
    photo: "arunachal-goulds-shortwing",
  },
  {
    id: "bhutan-2026-04",
    when: "2–27 Apr 2026",
    sort: "2026-04",
    place: "Bhutan, two back-to-back groups",
    country: "Abroad",
    species: "250+",
    guests: "A Taiwanese photography group, then an Indian group",
    text: "White-bellied Heron at the nest, watched from across the river so the birds were never disturbed. Red Panda, and Himalayan Monal photographed in falling snow.",
    ebird: "https://ebird.org/tripreport/503727",
    post: "DX3AyupmCfa",
    photo: "g-himalayan-cutia",
  },
  {
    id: "vietnam-2026-03",
    when: "Mar 2026 · 8 days",
    sort: "2026-03",
    place: "Southern Vietnam + Cambodia",
    country: "Abroad",
    species: "177",
    extra: "14 mammals & reptiles",
    text: "Eight hides in different habitats, Indian vegetarian food almost everywhere, then a Ha Long Bay cruise and the equinox sunrise at Angkor Wat. Next Vietnam–Cambodia trip: February 2027.",
    ebird: "https://ebird.org/tripreport/489368",
    post: "DWSff0LGE5F",
  },
  {
    id: "kashmir-2026-03",
    when: "Mar 2026",
    sort: "2026-03",
    place: "Kashmir",
    country: "India",
    text: "More than 20 Long-eared Owls at a single winter roost, found with Irfan Jeelani and Ansar Ahmad, pioneers of Kashmir birding.",
    post: "DVkDMmCAGbO",
    photo: "long-eared-owls-kashmir",
  },
  {
    id: "kerala-2026-02",
    when: "17–21 Feb 2026",
    sort: "2026-02",
    place: "Kerala: Thattekad and Munnar",
    country: "India",
    species: "139",
    text: "Almost every possible species of both sites photographed; a displaying Malabar Imperial Pigeon was the moment of the trip.",
    ebird: "https://ebird.org/tripreport/478702",
    post: "DVBXd1VE4gX",
  },
  {
    id: "costa-rica-2026-01",
    when: "Jan 2026",
    sort: "2026-01",
    place: "Costa Rica",
    country: "Abroad",
    species: "301",
    text: "The first Avian Trails group in five years to see all four Costa Rican monkeys. Sungrebe, Yellow-breasted Crake, Resplendent Quetzal, White-crested Coquette, a courting Montezuma Oropendola.",
    post: "DT_ym_AlY_8",
    photo: "costarica-quetzal",
    tour: "costa-rica",
  },
  {
    id: "corbett-trail-2025-12",
    when: "Dec 2025",
    sort: "2025-12",
    place: "Uttarakhand on Jim Corbett's trail",
    country: "India",
    species: "267",
    text: "From Corbett's village, Chhoti Haldwani, to Tanakpur where he shot three man-eaters. A tiger on the Jim Corbett Heritage Safari at the spot where he organised a hunt for the Viceroy; Black-throated Parrotbill at Munsyari.",
    ebird: "https://ebird.org/tripreport/441496",
    post: "DSTi7PNjk8C",
    photo: "group-chaukori-dawn",
  },
  {
    id: "mongolia-2025-10",
    when: "Oct 2025",
    sort: "2025-10",
    place: "Mongolia, the first trip",
    country: "Abroad",
    text: "A full day with a male Snow Leopard on a kill. Pallas's Cat, Takhi horses, eagle hunters, and a flock of about 500 Bohemian Waxwings over Ulaanbaatar.",
    post: "DczrXokEjcd",
    photo: "mongolia-snow-leopard",
    tour: "mongolia",
  },
  {
    id: "kenya-2025-09",
    when: "Sep 2025 · 12 days",
    sort: "2025-09",
    place: "Kenya, seven national parks",
    country: "Abroad",
    species: "354",
    extra: "44 mammals · 4 reptiles",
    text: "Cats in every park: three leopards, a rare Serval, 22 lions and three Cheetah sightings.",
    ebird: "https://ebird.org/tripreport/418715",
    post: "DPkt9Jdk_Rx",
    photo: "kenya-lodge-view",
  },
  {
    id: "ladakh-2025-09",
    when: "Sep 2025",
    sort: "2025-09",
    place: "Ladakh passage migrants",
    country: "India",
    species: "113",
    text: "An Icterine Warbler at Pangong Tso, the first record for India. A Mountain Weasel carrying a Ladakh Pika. Five high passes including Umling La.",
    ebird: "https://ebird.org/tripreport/413040",
    post: "DOznM0Zj9zu",
    photo: "icterine-warbler-first-record",
  },
  {
    id: "meghalaya-2025-09",
    when: "Aug–Sep 2025 · 3 days",
    sort: "2025-09",
    place: "Meghalaya",
    country: "India",
    species: "73",
    text: "Tawny-breasted Wren-babbler and Dark-rumped Swift, with local guide Prasanna Kalita; four waterfalls including Nohkalikai.",
    ebird: "https://ebird.org/tripreport/407167",
    post: "DOFP55_jw5a",
    photo: "meghalaya-wren-babbler",
    tour: "meghalaya",
  },
  {
    id: "ladakh-2025-08",
    when: "Jul–Aug 2025",
    sort: "2025-08",
    place: "Ladakh wildlife photography",
    country: "India",
    species: "95",
    text: "Menetries's Warbler, Eurasian Lynx and Pallas's Cat across two back-to-back groups.",
    ebird: "https://ebird.org/tripreport/401216",
    post: "DNIbx27tUJr",
    photo: "group-ladakh-2025",
  },
  {
    id: "borneo-2025-06",
    when: "Jun–Jul 2025",
    sort: "2025-06",
    place: "Borneo, two groups",
    country: "Abroad",
    species: "162",
    text: "Sunda Leopard Cat, Greater Mouse Deer, Proboscis Monkey and Orangutan. The second group logged 123 species.",
    ebird: "https://ebird.org/tripreport/388872",
    post: "DLV-aXQowHy",
    photo: "borneo-peacock-pheasant",
    tour: "borneo",
  },
  {
    id: "walong-2025-05",
    when: "May–Jun 2025",
    sort: "2025-05",
    place: "Walong and the Mishmi Hills",
    country: "India",
    species: "260",
    text: "Derbyan Parakeet, Chinese Vivid Niltava, Australasian Grass-Owl, Malayan Night Heron. Floods kept both groups from the White-bellied Heron.",
    post: "DKYSa1aAN6Q",
    photo: "group-arunachal-2025",
  },
  {
    id: "uttarakhand-2025-05",
    when: "May 2025",
    sort: "2025-05",
    place: "Uttarakhand: Kaladhungi, Munsyari, Darma, Sattal",
    country: "India",
    species: "230",
    guests: "A group from Chennai",
    text: "Golden Eagle, Cheer Pheasant, Himalayan Monal, Himalayan Cutia, Tawny Fish Owl, Himalayan Owl; Himalayan Tahr and Yellow-throated Marten.",
    ebird: "https://ebird.org/tripreport/369603",
    post: "DJ0FdyFvoDo",
  },
  {
    id: "bhutan-2025-04",
    when: "Apr 2025",
    sort: "2025-04",
    place: "Bhutan, Phuentsholing to Samdrup Jongkhar",
    country: "Abroad",
    species: "233",
    guests: "5 birders",
    text: "Red Panda and Himalayan Black Bear on a west-to-east crossing of the country.",
    ebird: "https://ebird.org/tripreport/358554",
    post: "DJA9dEygo2l",
  },
  {
    id: "costa-rica-2025",
    when: "Mar–Apr 2025",
    sort: "2025-04",
    place: "Costa Rica, two groups",
    country: "Abroad",
    species: "351",
    text: "Six species of manakin and five of toucan, Baird's Tapir, Agami Heron, Ornate Hawk-Eagle and Sunbittern.",
    ebird: "https://ebird.org/tripreport/350835",
    post: "DIX00CLB3C4",
  },
  {
    id: "colombia-2025-01",
    when: "Jan 2025",
    sort: "2025-01",
    place: "Colombia",
    country: "Abroad",
    species: "255",
    guests: "4 photographers",
    text: "An Andean Bear, seven species of antpitta and more than fifty hummingbirds.",
    ebird: "https://ebird.org/tripreport/317508",
    post: "DE9B7hPOCcY",
    photo: "group-colombia-feeders",
  },
  {
    id: "mizoram-2024-11",
    when: "Nov 2024",
    sort: "2024-11",
    place: "Mizoram",
    country: "India",
    species: "117",
    text: "Mount Victoria Babax, Chin Hills Wren-Babbler and Stripe-breasted Woodpecker. The easiest of the four targets, Hume's Treecreeper, got away.",
    ebird: "https://ebird.org/tripreport/296439",
    post: "DC8G7suBRiT",
  },
  {
    id: "madagascar-2024-10",
    when: "Oct 2024",
    sort: "2024-10",
    place: "Madagascar",
    country: "Abroad",
    species: "117",
    extra: "16 lemurs · 15 chameleons",
    text: "Five national parks, sunrise through the baobabs and a night-sky session.",
    ebird: "https://ebird.org/tripreport/288678",
    post: "DBxjNe9BNXw",
    photo: "madagascar-gecko",
    tour: "madagascar",
  },
  {
    id: "kenya-2024-10",
    when: "Oct 2024",
    sort: "2024-10",
    place: "Kenya",
    country: "Abroad",
    species: "380",
    extra: "33 mammals",
    guests: "Photographers from Malaysia and India",
    text: "Masai Mara and six more national parks, with macro photography of frogs as well.",
    ebird: "https://ebird.org/tripreport/284495",
    post: "DBIXAr_qovK",
    photo: "group-kenya-samburu",
  },
  {
    id: "png-2024-08",
    when: "Aug 2024",
    sort: "2024-08",
    place: "Papua New Guinea",
    country: "Abroad",
    species: "169",
    guests: "7 guests",
    text: "18 species of birds-of-paradise, 14 of them photographed well. Four provinces, three domestic flights.",
    ebird: "https://ebird.org/tripreport/270648",
    post: "C_UVlXZBY4b",
    photo: "png-flame-bowerbird",
    tour: "papua-new-guinea",
  },
  {
    id: "kinnaur-2024-06",
    when: "May–Jun 2024",
    sort: "2024-06",
    place: "Kinnaur, Himachal Pradesh",
    country: "India",
    species: "162",
    guests: "3 back-to-back groups",
    text: "Three back-to-back groups through the Kinnaur valley.",
    ebird: "https://ebird.org/tripreport/249611",
    post: "C78BBEFhy7d",
  },
  {
    id: "gangotri-2024-03",
    when: "Mar 2024",
    sort: "2024-03",
    place: "Gangotri National Park",
    country: "India",
    text: "A group trip into the Bhagirathi valley that Rajesh and Sheela scouted in 2021.",
    ebird: "https://ebird.org/tripreport/217018",
    post: "C5MtaYSB3uZ",
    photo: "harsil-white-throated-bushtit",
    tour: "rajaji-bhagirathi-valley",
  },
  {
    id: "kumaon-2024-03",
    when: "Mar 2024 · 9 days",
    sort: "2024-03",
    place: "Kaladhungi – Manila – Munsyari",
    country: "India",
    species: "262",
    guests: "A group of birders from Pune",
    text: "Both Avian Trails lodges and the high country beyond; Chestnut-headed Tesia at Munsyari.",
    ebird: "https://ebird.org/tripreport/214970",
    post: "C46w1X8hWX-",
  },
  {
    id: "costa-rica-2024",
    when: "Feb–Mar 2024",
    sort: "2024-02",
    place: "Costa Rica, two groups",
    country: "Abroad",
    species: "307",
    guests: "9 photographers",
    text: "Both groups photography-only, still 307 species, and 39 lifers for Rajesh.",
    ebird: "https://ebird.org/tripreport/208550",
    post: "C4CO7YmKNrE",
    photo: "costarica-red-headed-barbet",
  },
];
